export const PLACE_PIECE = 'PLACE_PIECE';
export const SHUFFLE_PIECES = 'SHUFFLE_PIECES';
export const POPULATE_NEXT = 'POPULATE_NEXT';
export const POPULATE_CURR = 'POPULATE_CURR';
export const CHOOSE_STARTING_PLAYER = 'CHOOSE_STARTING_PLAYER';
export const QUEUE_PIECE = 'QUEUE_PIECE';
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION';